### ISSUE TITLE
Potential problem with TimeToLive field in HttpMessage and XmppMessage

### ISSUE THREAD

**Issue by karapas** [google/go-gcm#27]
Hi folks,
I noticed that the TimeToLive field in the message structs is tagged as `json:"time_to_live,omitempty". From what I understand, this means that if TimeToLive has the default value (zero), then it will be omitted when marshaling the struct. If this is indeed the case (and according to my tests it is), then there is a discrepancy in the time_to_live usage, according to [https://developers.google.com/cloud-messaging/http-server-ref]:
time_to_live = 0, means that the notification should not be throttled and delivered immediately, and if this is not possible, then it should be discarded. However if I set TimeToLive = 0, it will be omitted from the message sent to the GCM server, and then the server will assume the default value, which is 4 weeks -- clearly, not what my intention was.

**Comment by aliafshar** [comment]
This could be fixed using an int pointer field (like all the other libraries do)

**Comment by karapas** [comment]
Yes, that sounds good

**Comment by silvolu** [comment]
Fixed, apologies for the delay.

**Comment by karapas** [comment]
Great thanks!
