### ISSUE TITLE
Incorrect XMPP user string generation

### ISSUE THREAD

**Issue by szpakas** [google/go-gcm#29]
Hi,

xmppUser method is generating XMPP user string by concatenating "senderId" with "xmppHost". It's a problem as host is set to "gcm-xmpp.googleapis.com". This results in auth error as GCM seems to be accepting only "senderId@xmpp.googleapis.com" as user. Changing "xmppHost" const to "xmpp.googleapis.com" solves the problem.

If my assumption on the problem is correct, I would suggest separating xmppHost from user string generation.

**Comment by silvolu** [comment]
You are indeed right, apologies for missing this and for the delay in fixing.
