### ISSUE TITLE
FCM

### ISSUE THREAD

**Issue by Andrushk** [google/go-gcm#31]
What about: Firebase Cloud Messaging (FCM) is the new version of GCM. It inherits the reliable and scalable GCM infrastructure, plus new features! See the FAQ to learn more. If you are integrating messaging in a new app, start with FCM. GCM users are strongly recommended to upgrade to FCM, in order to benefit from new FCM features today and in the future.

How to use FCM endpoints?
fcm.googleapis.com/fcm/ and fcm-xmpp.googleapis.com

**Comment by urjitbhatia** [comment]
Summoning @silvolu : Do we need to change anything for the FCM migration (other than the endpoints maybe?) Or is that fixed with: https://github.com/google/go-gcm/commit/1708036c4639349562068ad2d4df2364cd0a1004

cc: @nickb1080
Thanks!

**Comment by kroikie** [comment]
There are no changes required on the server side to use FCM. You can update to the new endpoints, but the old gcm endpoints will continue to work.

**Comment by appleboy** [comment]
I send the [PR](https://github.com/google/go-gcm/pull/32) to change new end point entry.

**Comment by silvolu** [comment]
As mentioned by @kroikie, there is no need to update to the new endpoints. If and when there will be more substantial changes on the api side, we might think of forking into a new go-fcm library.

**Comment by codingzombie** [comment]
@silvolu @kroikie  When will a go-fcm library be released?
