### ISSUE TITLE
Listen connection dropping - use model

### ISSUE THREAD

**Issue by kuchlous** [google/go-gcm#40]
This is more of a usage question. I have started using this code in a server to listen to incoming GCM messages. I noticed that the GCM's stopped reaching my server suddenly but on restarting the server I got all the queued up GCM's. I am guessing that the listen connection had dropped in the night.

Should the the gcm.Listen call be in a forever loop like so:

```
func (r *Receiver) startListener() {
	for {
		err := gcm.Listen(r.gcmSenderId, r.googleApiKey, messageHandler, stopChannel)
		revel.INFO.Println("Restarted listener because of err", err)
	}
}
```

**Comment by bolshoy** [comment]
Not exactly. You don't always know that the connection has dropped. The best way is to send periodic pings and recreate your client when ping times out. You can get some ideas in our fork here: https://github.com/rounds/go-gcm/blob/master/xmpp_client.go

**Comment by kuchlous** [comment]
Once in a while my listener is dying with the error:

error on Recv>XML syntax error on line 1: unexpected EOF

Once it dies, it keeps getting this error again and again. Also, when the listener comes out it does not seem to finish the 'go' routine with the result that my process runs out of memory.

**Comment by kuchlous** [comment]
@bolshoy , I see that you have commented out the monitoring code in your fork. Is it not needed? Or was it giving some problem?

```
104   // Ping periodically and indentify xmpp disconnect.
105   //go c.monitorConnection()

```

**Comment by bolshoy** [comment]
@kuchlous right, it used to cause some problems during the connection draining, and I haven't checked it properly since then. Thanx for reminding me.

**Comment by kuchlous** [comment]
@bolshoy , so are you able to use the listener reliably without the monitoring? Or are you saying that you actually have monitoring turned on in your production code? BTW, thanks for all your work and prompt replies.

**Comment by bolshoy** [comment]
@kuchlous the clients runs good on production with monitoring disabled, but it does not handle lost connecitons properly. I am reworking it now, stay tuned.

**Comment by kuchlous** [comment]
@bolshoy , Thank you. Will wait for your update.

**Comment by bolshoy** [comment]
@kuchlous ready, give it a try.

**Comment by kuchlous** [comment]
@bolshoy , can you think of a way to simulate ping timeout from google GCM server? Without that will be difficult to verify that it working.

**Comment by bolshoy** [comment]
@kuchlous you can comment out the line https://github.com/rounds/go-gcm/blob/master/xmpp_client.go#L246 , this will simulate "no pongs" situation.
Also you may use tcpkill utility to simulate sudden connection drops.

**Comment by kuchlous** [comment]
@bolshoy , the code is working flawlessly. No problems for more than week. Thanks.

**Comment by bolshoy** [comment]
@kuchlous  thanx! :+1:
